#!/usr/bin/env bash
# Local Inoreader-style feed reader — control menu.
#
#   ./scripts/start_reader.sh             interactive menu (start/stop/restart/status…)
#   ./scripts/start_reader.sh status      one-shot action, same as the menu items:
#   ./scripts/start_reader.sh start
#   ./scripts/start_reader.sh stop
#   ./scripts/start_reader.sh restart
#   ./scripts/start_reader.sh logs
#   ./scripts/start_reader.sh open
#   ./scripts/start_reader.sh regen     regenerate all feeds locally (long)
#
# Port override:  PORT=9000 ./scripts/start_reader.sh
set -euo pipefail

# ---- configuration ---------------------------------------------------------
ROOT=$(cd "$(dirname "$0")/.." && pwd)
PORT="${PORT:-8080}"
LOG=/tmp/rss-reader.log
URL="http://localhost:$PORT/reader"
# Bracket trick ([l]) so pgrep/pkill don't match THIS script's own command line.
READER_PATTERN="[l]ocal_reader\.py"

# ---- terminal colors -------------------------------------------------------
_C='\033[0m'
_BOLD='\033[1m'
_GREEN='\033[0;32m'
_RED='\033[0;31m'
_YELLOW='\033[0;33m'
_CYAN='\033[0;36m'
_MAGENTA='\033[0;35m'
_BLUE='\033[0;34m'
_DIM='\033[2m'

color()   { printf "${1}%s${_C}" "$2"; }
c_green()  { color "$_GREEN"  "$*"; }
c_red()    { color "$_RED"    "$*"; }
c_yellow() { color "$_YELLOW" "$*"; }
c_cyan()   { color "$_CYAN"   "$*"; }
c_magenta(){ color "$_MAGENTA" "$*"; }
c_bold()   { color "$_BOLD"   "$*"; }
c_dim()    { color "$_DIM"    "$*"; }

# ---- helpers ---------------------------------------------------------------
reader_pid() { pgrep -f "$READER_PATTERN" 2>/dev/null | head -1 || true; }
is_running() { [ -n "$(reader_pid)" ]; }

feed_count() { find "$ROOT/feeds" -maxdepth 1 -name '*.xml' 2>/dev/null | wc -l | tr -d ' '; }

kill_reader() {
    pkill -f "$READER_PATTERN" 2>/dev/null || true
    # Wait for it to actually exit (then escalate to KILL if needed).
    for _ in $(seq 1 15); do
        is_running || return 0
        sleep 0.3
    done
    pkill -9 -f "$READER_PATTERN" 2>/dev/null || true
    sleep 0.3
}

open_browser() {
    local url="$1"
    if command -v xdg-open >/dev/null 2>&1; then
        (xdg-open "$url" >/dev/null 2>&1 &)
    elif command -v open >/dev/null 2>&1; then
        (open "$url" >/dev/null 2>&1 &)
    elif command -v python3 >/dev/null 2>&1; then
        python3 -c "import webbrowser,sys; webbrowser.open(sys.argv[1])" "$url"
    else
        printf 'Open this in your browser: %s\n' "$url"
    fi
}

# ---- actions ---------------------------------------------------------------
action_start() {
    if is_running; then
        c_yellow "Reader is already running"
        return 0
    fi
    local n
    n=$(feed_count)
    if [ "$n" -eq 0 ]; then
        c_yellow "No feeds found in $ROOT/feeds (they are generated by CI or the local pipeline)."
        printf '%s\n' "    PYTHONPATH=. python3 scripts/generate_feeds.py"
    fi

    pkill -f "$READER_PATTERN" 2>/dev/null || true
    # Fresh log per start; PYTHONUNBUFFERED keeps prints live in the log.
    setsid nohup env PYTHONUNBUFFERED=1 python3 "$ROOT/scripts/local_reader.py" "$PORT" --no-browser \
        >"$LOG" 2>&1 < /dev/null &

    # The reader is a detached child of $!; give it a beat to bind the port.
    sleep 1
    if curl -s -o /dev/null --max-time 3 "$URL"; then
        c_green "Reader started:  $URL"
        printf 'Log: %s\n' "$LOG"
        c_dim "Use: $0 stop (or the menu) to stop it."
    else
        c_red "Reader failed to start. Tail of log:"
        tail -5 "$LOG" 2>/dev/null || true
        return 1
    fi
}

action_stop() {
    if ! is_running; then
        c_yellow "Reader is not running"
        return 0
    fi
    kill_reader
    if is_running; then
        c_red "Could not stop the reader: pid $(reader_pid)"
        return 1
    fi
    c_red "Reader stopped"
}

action_restart() {
    action_stop || true
    action_start
}

action_status() {
    local pid
    pid=$(reader_pid)
    if [ -n "$pid" ]; then
        c_green "● Running"
        printf '  PID        : %s\n' "$pid"
        printf '  URL        : %s\n' "$URL"
        printf '  Feeds      : %s files in %s\n' "$(c_cyan "$(feed_count)")" "$ROOT/feeds"
        if curl -s -o /dev/null --max-time 3 "$URL"; then
            printf '  HTTP       : %s\n' "$(c_green OK)"
        else
            printf '  HTTP       : %s\n' "$(c_red "no response")"
        fi
        printf '  Process    : %s\n' "$(ps -p "$pid" -o args= 2>/dev/null | cut -c1-100)"
        if [ -f "$LOG" ]; then
            printf '  Log tail   :\n'
            tail -3 "$LOG" | sed 's/^/    /'
        fi
    else
        c_red "● Not running"
        printf '  Start with : %s\n' "$(c_yellow "$0 start")"
        if [ -f "$LOG" ]; then
            printf '  Last log   :\n'
            tail -3 "$LOG" | sed 's/^/    /'
        fi
    fi
}

action_logs() {
    if [ -f "$LOG" ]; then
        printf '%s\n' "$(c_cyan "=== $LOG ===")"
        tail -n 30 "$LOG"
    else
        c_yellow "No log file yet ($LOG)"
    fi
}

action_open() {
    if ! is_running; then
        c_yellow "Reader not running — starting it first"
        action_start
    fi
    open_browser "$URL"
    c_green "Opened $URL"
}

# Regenerate feeds locally: the same pipeline GitHub Actions runs.
# generate is the long step (scrapes every site); the rest enrich/format it.
action_regen() {
    local steps_l
    steps_l=(
        "generate_feeds.py:Step 1/4 — scrape all sites"
        "enrich_posters.py:Step 2/4 — enrich with TMDb posters/years/links"
        "fix_feeds.py:Step 3/4 — post-process (year format, link fixes)"
        "generate_index.py:Step 4/4 — rebuild index.html + feeds.opml"
    )
    (
        cd "$ROOT" || exit 1
        export PYTHONPATH="$ROOT${PYTHONPATH:+:${PYTHONPATH}}"
        for entry in "${steps_l[@]}"; do
            script=${entry%%:*}
            label=${entry#*:}
            printf '%s\n' "$(c_magenta "▶ $label")"
            if ! python3 "scripts/$script"; then
                printf '%s\n' "$(c_red "  ✗ $script failed")"
                exit 1
            fi
        done
    ) || {
        c_red "Regeneration failed — see output above."
        return 1
    }
    printf '%s\n' "$(c_green "✓ Regenerated $(feed_count) feeds into $ROOT/feeds")"
    c_dim "Enrichment needs TMDB_API_KEY, else that step is skipped (CI has it)."
    c_dim "Refresh the reader tab (F5 / Ctrl+Shift+R) to pick up new feeds."
}

# ---- interactive menu ------------------------------------------------------
banner() {
    printf '\n'
    printf '%s\n' "$(c_bold "$(c_magenta '  🡇  RSS Feed Reader — control menu')")"
    printf '%s\n' "$(c_dim       '  ────────────────────────────────────────')"
    printf '%s\n' "$(c_dim       "  URL: $URL   ·   Port: $PORT")"
    printf '%s\n'
}

show_menu() {
    printf '  %s start\n'     "$(c_green  ' 1)')"
    printf '  %s restart\n'   "$(c_yellow ' 2)')"
    printf '  %s stop\n'      "$(c_red    ' 3)')"
    printf '  %s status\n'    "$(c_cyan   ' 4)')"
    printf '  %s tail log\n'  "$(c_cyan   ' 5)')"
    printf '  %s open browser\n' "$(c_cyan ' 6)')"
    printf '  %s regenerate feeds (local)\n' "$(c_magenta ' 7)')"
    printf '  %s quit\n'      "$(c_dim    ' 8)')"
    printf '\n'
}

menu() {
    while true; do
        clear 2>/dev/null || true
        banner
        show_menu
        printf '  %s' "$(c_bold "Your choice? ")"
        read -r choice || { printf '\n'; break; }
        case "${choice%%[!0-9]*}" in
            1) action_start ;;
            2) action_restart ;;
            3) action_stop ;;
            4) action_status ;;
            5) action_logs ;;
            6) action_open ;;
            7) action_regen ;;
            8) break ;;
            *) c_yellow "Invalid choice — pick 1–8." ;;
        esac
        printf '\n  %s' "$(c_dim "Press Enter to return to the menu…")"
        read -r _ || break
    done
}

# ---- dispatch --------------------------------------------------------------
case "${1:-menu}" in
    start)  action_start ;;
    stop)   action_stop ;;
    restart) action_restart ;;
    status) action_status ;;
    logs|log) action_logs ;;
    open|browse|browser) action_open ;;
    regen|refresh|generate|gen) action_regen ;;
    menu)   menu ;;
    -h|--help|help) sed -n '2,14p' "$0" ;;
    *)
        c_red "Unknown action: ${1:-}"
        printf '  Try: %s start|stop|restart|status|logs|open|regen\n' "$(basename "$0")"
        exit 2
        ;;
esac
